### ISSUE TITLE
Issue with proof of unforgeability of ASNL

### ISSUE THREAD

**Issue by RandomRun** [monero-project/research-lab#4]
In the proof it is assumed, by contradiction, that there exists an adversary _A_ that is able to forge the ASNL, but later on something much stronger is assumed, namely that _A_ somehow knows the discrete logs of _L_-values to be numbers _a_ and _b_. I don't see how that could be implied by _A_'s ability to produce a forged signature. Isn't it possible that _A_ has a way to produce _L_\- and _s_-values that form a valid signature without knowing the discrete log of the _L_'s? If so, the proof shouldn't use the numbers _a_ and _b_.

**Comment by divbit** [comment]
Hi, the paper states that it is a sketch of a proof (mainly it's a sketch because the things are no more efficient than the Borromean ones which are mentioned could be used on a previous page, and possibly less efficient according to the Borromean paper, in some cases (e.g. higher bases than 2 or whatever, and I guess at the time of writing the Borromean paper didn't have a proof written out, but it was sort of publicly in progress on their github, so the author didn't want to sort of steal possibly a big chunk of their paper).

Anyway, I think the point in assuming the 'a', 'b' values is that since various other bits of information are determined by the time-travel stuff (since you have to produce L1, L2 before knowing c1, c2) then at the end you need to find a scalar 's' so would need some way to get a scalar from the other bits of information which are already determined at that point). Moving sG by itself, it is easier to find an 's' when you already know a,b, so presumably if you can't find 's' with that advantage, then you can't find 's' without the advantage. But- this section of the paper hasn't been reviewed much, and it is just a sketch, so let me know if you see an error in that. BTW, the author e-mail is apparently not provided at the paper, so one might assume they are not open to correspondence, however, it's sort of publicly known from their github (shen.noether@gmx.com) which is linked on the first page of the paper, so I would assume they are open to correspondence for this type of question.

**Comment by ShenNoether** [comment]
2p: Since I'm no longer actively working on this stuff- the Monero community could try and get someone to audit- off the top of my head there is NCC crypto services or coinspect. For example, I think Zcash recently did an audit with the first of the two. I can name bugs that have been found in almost every big crypto thing that I can think of off the top of my head, so I wouldn't be too unsurprised if I wasn't immune.

**Comment by divbit** [comment]
After pondering this in the back of my head for a day, I came up with a possible attack vector here based on my previous comment: I think you should commit to all of the P before computing the c_1, c_2 in order for my previous comment to be correct. I've included a quick fix at my fork of the repo which hopefully mitigates that. (Note that there might be a trivial case where you can forge a 0 output if you took P1 - P1 or something, but afaict, that doesn't seem to bad). In any case, the comment above is probably a good idea as well.

**Comment by divbit** [comment]
I sent an introductory e-mail between Alex Balducci at NCC and fluffypony (I guess the main xmr guy) for the benefit of the Monero community in case they want to follow the suggestion of the previous comment (I don't personally have the time / incentive to support the software, nor am I an investor). If R.R. would like to discuss the math further, I would be honored to (either here or at my personal e-mail divbit@mail.com) - note that these signatures were moved to the appendix in an August draft of the paper, which, for reasons stated in my first comment is probably a more appropriate place for them, although I think the proof sketch remains roughly the same.

**Comment by divbit** [comment]
I previously noted that there was a flaw in my previous comment- and that one needs to commit to the L_0 values. After working this change through on paper, I realized that doing this reduces to the Borromean sigs in any case.

**Comment by ShenNoether** [comment]
It's probably worth noting, that shortly after this thread first appeared, there was a (I think reasonable) offer setup for a crypto audit between one of the organizations in the previous comment, and Riccardo / Othe of the monero project. I'm not sure whether the monero guys followed through, but it would be nice to hear the results of that.

**Comment by ShenNoether** [comment]
I would like to point out that there is now a thread claiming I completed a 'deep code review' on reddit. I tried to comment there and point out this is untrue (I fixed a small piece of the borromean sigs, and compared the hash to point function with OWS recent implementation), but the comment got shadow-deleted or something.

**Comment by RandomRun** [comment]
Hi Shen. Thank you for setting the record straight on this thread. Could you please provide the link to the Reddit thread and your comment, if possible? I couldn't find it there. If something like that was deliberately deleted that is very concerning on its own right...

**Comment by fluffypony** [comment]
It was censored by Theymos! Quick everyone, let's head to /r/btc!

/s

**Comment by ShenNoether** [comment]
@RandomRun https://unreddit.com/r/Monero/comments/5lyw05/funding_required_shen_noether_for_work_on_ringct/

**Comment by taushet** [comment]
...so why was that comment deleted? @fluffypony

**Comment by fluffypony** [comment]
@taushet because the comment was so out of bounds, and Shen hadn't contacted myself or othe privately, that it was a safe assumption that his account had been compromised. At this stage I'm still assuming his account has been compromised and am disregarding anything he has said publicly.
